# instructions to use dreamtools inside a Fedora docker (22)

FROM fedora:22
MAINTAINER Thomas Cokelaer

RUN echo "0.10.4" > /version

ADD dreamtools_install.sh /

RUN /bin/bash /dreamtools_install.sh
#EXPOSE 8100

